// Copies the ABIs the app and keepers need from Foundry artifacts into typed `as const` modules.
// Usage: (cd contracts && forge build) && node scripts/export-abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");

const contracts = [
  ["ManagerVault", "ManagerVault.sol"],
  ["VaultFactory", "VaultFactory.sol"],
  ["TradeExecutor", "TradeExecutor.sol"],
  ["PerformanceTracker", "PerformanceTracker.sol"],
  ["FollowerStops", "FollowerStops.sol"],
  ["Guardrails", "Guardrails.sol"],
  ["FeeEngine", "FeeEngine.sol"],
  ["OracleAdapter", "OracleAdapter.sol"],
  ["MarketClock", "MarketClock.sol"],
  ["FeeCollector", "FeeCollector.sol"],
  ["ProjectTokenHooks", "ProjectTokenHooks.sol"],
  ["IERC20Metadata", "IERC20Metadata.sol"],
];

let ts = "// AUTO-GENERATED by scripts/export-abis.mjs from contracts/out — do not edit.\n\n";
for (const [name, file] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
  const id = name === "IERC20Metadata" ? "erc20" : name[0].toLowerCase() + name.slice(1);
  ts += `export const ${id}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
for (const target of [join(root, "app", "src", "config", "abis.ts"), join(root, "scripts", "src", "abis.ts")]) {
  writeFileSync(target, ts);
  console.log("wrote", target);
}
